package bean;
// Generated 04/12/2023 10:00:31 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MebVendasProduto generated by hbm2java
 */
@Entity
@Table(name="meb_vendasProduto"
    ,catalog="db_maria_borba"
)
public class MebVendasProduto  implements java.io.Serializable {


     private int idMebVendasProduto;
     private MebProdutos mebProdutos;
     private MebVendas mebVendas;
     private double mebQuantidade;
     private double mebValorUni;

    public MebVendasProduto() {
    }

    public MebVendasProduto(int idMebVendasProduto, MebProdutos mebProdutos, MebVendas mebVendas, double mebQuantidade, double mebValorUni) {
       this.idMebVendasProduto = idMebVendasProduto;
       this.mebProdutos = mebProdutos;
       this.mebVendas = mebVendas;
       this.mebQuantidade = mebQuantidade;
       this.mebValorUni = mebValorUni;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_meb_vendasProduto", unique=true, nullable=false)
    public int getIdMebVendasProduto() {
        return this.idMebVendasProduto;
    }
    
    public void setIdMebVendasProduto(int idMebVendasProduto) {
        this.idMebVendasProduto = idMebVendasProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_meb_produtos", nullable=false)
    public MebProdutos getMebProdutos() {
        return this.mebProdutos;
    }
    
    public void setMebProdutos(MebProdutos mebProdutos) {
        this.mebProdutos = mebProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_meb_vendas", nullable=false)
    public MebVendas getMebVendas() {
        return this.mebVendas;
    }
    
    public void setMebVendas(MebVendas mebVendas) {
        this.mebVendas = mebVendas;
    }

    
    @Column(name="meb_quantidade", nullable=false, precision=22, scale=0)
    public double getMebQuantidade() {
        return this.mebQuantidade;
    }
    
    public void setMebQuantidade(double mebQuantidade) {
        this.mebQuantidade = mebQuantidade;
    }

    
    @Column(name="meb_valorUni", nullable=false, precision=22, scale=0)
    public double getMebValorUni() {
        return this.mebValorUni;
    }
    
    public void setMebValorUni(double mebValorUni) {
        this.mebValorUni = mebValorUni;
    }




}


