package bean;
// Generated 04/12/2023 10:00:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MebVendas generated by hbm2java
 */
@Entity
@Table(name="meb_vendas"
    ,catalog="db_maria_borba"
)
public class MebVendas  implements java.io.Serializable {


     private int idMebVendas;
     private MebClientes mebClientes;
     private MebUsuarios mebUsuarios;
     private double mebTotal;
     private Date mebData;

    public MebVendas() {
    }

	
    public MebVendas(int idMebVendas, MebClientes mebClientes, MebUsuarios mebUsuarios, double mebTotal) {
        this.idMebVendas = idMebVendas;
        this.mebClientes = mebClientes;
        this.mebUsuarios = mebUsuarios;
        this.mebTotal = mebTotal;
    }
    public MebVendas(int idMebVendas, MebClientes mebClientes, MebUsuarios mebUsuarios, double mebTotal, Date mebData) {
       this.idMebVendas = idMebVendas;
       this.mebClientes = mebClientes;
       this.mebUsuarios = mebUsuarios;
       this.mebTotal = mebTotal;
       this.mebData = mebData;
    }
   
     @Id 

    
    @Column(name="id_meb_vendas", unique=true, nullable=false)
    public int getIdMebVendas() {
        return this.idMebVendas;
    }
    
    public void setIdMebVendas(int idMebVendas) {
        this.idMebVendas = idMebVendas;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_meb_clientes", nullable=false)
    public MebClientes getMebClientes() {
        return this.mebClientes;
    }
    
    public void setMebClientes(MebClientes mebClientes) {
        this.mebClientes = mebClientes;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_meb_usuario", nullable=false)
    public MebUsuarios getMebUsuarios() {
        return this.mebUsuarios;
    }
    
    public void setMebUsuarios(MebUsuarios mebUsuarios) {
        this.mebUsuarios = mebUsuarios;
    }

    
    @Column(name="meb_total", nullable=false, precision=22, scale=0)
    public double getMebTotal() {
        return this.mebTotal;
    }
    
    public void setMebTotal(double mebTotal) {
        this.mebTotal = mebTotal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="meb_data", length=10)
    public Date getMebData() {
        return this.mebData;
    }
    
    public void setMebData(Date mebData) {
        this.mebData = mebData;
    }


}


